#!/bin/sh

echo CODA_BUNDLE_PATH: $CODA_BUNDLE_PATH
echo CODA_BUNDLE_SUPPORT: $CODA_BUNDLE_SUPPORT
echo CODA_FILEPATH: $CODA_FILEPATH
echo CODA_LINE_ENDING: $CODA_LINE_ENDING
echo CODA_LINE_INDEX: $CODA_LINE_INDEX
echo CODA_LINE_NUMBER: $CODA_LINE_NUMBER
echo CODA_SELECTED_TEXT: $CODA_SELECTED_TEXT
echo CODA_SITE_LOCAL_PATH: $CODA_SITE_LOCAL_PATH
echo HOME: $HOME
